version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: build/Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"

  db:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
